### ISSUE TITLE
RNG without replacement

### ISSUE THREAD

**Issue by Cyttorak** [Mpstark/RandomCampaignStart#3]
Hi. I've played with some of the settings in version 1.0 and it seems that the RNG is randomly choosing from the defined 'Mech lists without replacement. My random list for light 'Mechs only contains 4 models, and when you randomly pick 4 lights at the start of a new campaign, it always generates those 4 'Mechs without any duplication (although the order will change). Instead, you ought to be able to generate several of the same model.

This method is appropriate for generating random pilots, where you don't want duplication, but not for 'Mechs.

Also, a request: is it possible to insert code for each 'Mech in the list that weights the choice? I think currently there must be an equal probability of generating each 'Mech.

Finally, may I post a version of this (with some of my alterations) to nexusmods.com?

**Comment by Mpstark** [comment]
The behavior you are describing is intended. If you would like to have chances of duplicates, you can duplicate the entries in the list.

Regarding weighting, I'm not particularly interested in this functionality -- I would perhaps accept a PR for it, but I'm not going to actively pursue it myself. You could do a poor mans weighting and use duplicates in the mech lists.

I'd rather you didn't post this to the Nexus, I'm planning on doing that myself at some point in the near future.

**Comment by Cyttorak** [comment]
I already came to the same conclusion as you did regarding the weighting and duplication, and those are some of the changes in my version. So for example, my 'Mech list includes several entries for "Locust 1V", in order to correctly weight the distribution. Was tested, and works as theorized.

I'll wait for your version to be posted before suggesting any additions. BTW, I think the Nexus community could benefit from your mods, several of which I don't see duplicates/replacements for. Good work.
